project_name: snake-map-gen

before:
  hooks:
    - go mod tidy
    
builds:    
  -
    binary: snake-map-gen
    goos:
      - linux
      - windows
      - darwin

    goarch:
      # Architectures for executable binary generation
      - amd64
      - arm64
      - arm
      - 386

      # # Specifying all architectures for .deb and .rpm generation
      # - 386
      # - amd64
      # - arm
      # - arm64
      # - ppc64
      # - ppc64le
      # - mips
      # - mipsle
      # - mips64
      # - mips64le
    
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.txt
      - README.md
    
    replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      amd64: amd64_64bit
      arm64: arm64_64bit
      386: i386_32bit
      arm: armv6_32bit

checksum:
  name_template: 'sha256_checksums.txt'
  algorithm: sha256
  
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: snake-map-gen

    tap:
      owner: MiloAkerman
      name: homebrew-snake-map-gen

    url_template: https://github.com/MiloAkerman/snake-map-gen/releases/download/{{ .Tag }}/{{ .ArtifactName }}

    commit_author:
      name: MiloAkerman
      email: your-email@example.com

    homepage: https://github.com/MiloAkerman/snake-map-gen
    description: Convert images into compressed ascii art for snake maps
    license: Apache 2.0
    skip_upload: true

    test: |
      system "#{bin}/snake-map-gen --version"

    install: |
      bin.install "snake-map-gen"

nfpms:
  -
    package_name: snake-map-gen
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      
    homepage: https://github.com/MiloAkerman/snake-map-gen
    vendor: MiloAkerman
    maintainer: MiloAkerman <your-email@example.com>
    description: Convert images into compressed ascii art for snake maps
    license: Apache 2.0

    formats:
      - deb
      - rpm
      
    release: 1
    section: graphics
    priority: optional
    bindir: /usr/bin
    
    rpm:
      compression: lzma
